config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views

from star_wars.common.views import MainView

urlpatterns = [
    path(settings.ADMIN_URL, admin.site.urls),
    path("", MainView.as_view(), name='main'),
    path("films/", include("star_wars.films.urls", namespace="films")),
    path("users/", include("star_wars.users.urls", namespace="users")),
    path("web_history/", include("star_wars.url_history.urls", namespace='web_history')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

star_wars/films/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from star_wars.films.views import FilmView, FilmApiView, FilmDetailView

router = DefaultRouter()
router.register(r'film', FilmApiView, base_name='film')

app_name = 'films'
urlpatterns = [
    path('api/', include(router.urls)),
    path('', view=FilmView.as_view(), name='index'),
    path('detail/<int:id>', FilmDetailView.as_view(), name='detail')
    # path('list/', )
]

star_wars/url_history/urls.py
from django.urls import path

from star_wars.url_history.views import UrlHistoryView


app_name = 'web_history'
urlpatterns = [
    path('list/', UrlHistoryView.as_view(), name='list')
]

star_wars/users/urls.py
from django.urls import path

from star_wars.users.views import RegisterUserView, LoginUserView, LogOutView

app_name = "users"
urlpatterns = [
    path("register/", view=RegisterUserView.as_view(), name='register'),
    path("login/", view=LoginUserView.as_view(), name='login'),
    path("logout/", view=LogOutView.as_view(), name='logout')
]

star_wars/characters/models.py
# -*- coding: utf-8 -*-

from random import randint

from django.db.models import CharField, TextField, ImageField, ManyToManyField
from django.utils.translation import ugettext_lazy as _
from model_utils.models import TimeStampedModel


GENDER_CHOICES = (
    ('Male', _("Hombre")),
    ('Female', _('Mujer')),
    ('unknown', _("Desconocido")),
    ('n/a', _("N/A"))
)


class Character(TimeStampedModel):
    name = CharField(max_length=255)
    birth_year = CharField(max_length=255)
    eye_color = CharField(max_length=255)
    gender = CharField(max_length=255, choices=GENDER_CHOICES)
    hair_color = CharField(max_length=255)
    height = CharField(max_length=255)
    mass = CharField(max_length=255)
    skin_color = CharField(max_length=255)
    homeworld = CharField(max_length=255)
    url = TextField()
    character_image = ManyToManyField('CharacterImage', blank=True)

    class Meta:
        verbose_name = _("Personaje")
        verbose_name_plural = _("Personajes")

    @property
    def random_image(self):
        queryset = self.character_image.all()
        count = queryset.count()
        random_index = randint(0, (count or 1) - 1)
        try:
            return queryset[random_index].image
        except IndexError:
            return None

    @property
    def description(self):
        pronoun = 'her' if self.gender in ['Female'] else ('his' if self.gender in ['Male'] else 'its')
        data = {**{'pronoun': pronoun, 'pronoun_c': pronoun.capitalize()}, **self.__dict__}
        description = "%(name)s was born in %(birth_year)s. %(pronoun_c)s eyes are %(eye_color)s and %(pronoun)s hair " \
                      "is %(hair_color)s. " \
                      "Height %(height)s & weight %(mass)s. Residence home: %(homeworld)s" % data
        return description


class CharacterImage(TimeStampedModel):
    image = ImageField(upload_to='characters/uploaded', default='characters/default/default.jpg')

    class Meta:
        verbose_name = _("Image de Personaje")
        verbose_name_plural = _("Image de Personajes")

star_wars/films/models.py
from django.db.models import CharField, IntegerField, TextField, DateField, ManyToManyField, ImageField
from django.utils.translation import ugettext_lazy as _
from model_utils.models import TimeStampedModel

from star_wars.characters.models import Character


class Film(TimeStampedModel):
    title = CharField(max_length=255)
    episode_id = IntegerField()
    opening_crawl = TextField()
    director = CharField(max_length=255)
    producer = CharField(max_length=255)
    release_date = DateField()
    characters = ManyToManyField(Character)
    url = TextField()
    image = ImageField(default='films/default/default.jpg', upload_to='films/uploaded')

    class Meta:
        verbose_name = _("Película")
        verbose_name_plural = _("Películas")

star_wars/url_history/models.py
# -*- coding: utf-8 -*-

from django.contrib.auth import get_user_model
from django.utils.translation import ugettext_lazy as _
from django.db import models
from django.db.models import ForeignKey, URLField
from model_utils.models import TimeStampedModel

User = get_user_model()


class UrlHistory(TimeStampedModel):
    user = ForeignKey(User, on_delete=models.CASCADE)
    url = URLField(max_length=255)

    class Meta:
        verbose_name = _("Histórico de URL visitada")
        verbose_name_plural = _("Histórico de URLs visitadas")

star_wars/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = CharField(_("Name of User"), blank=True, max_length=255)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

star_wars/films/forms.py
from django.forms import forms


class SearchFilmForm(forms.Form):
    class Meta:
        fields = ("search", )

star_wars/users/forms.py
# -*- coding: utf-8 -*-

import logging

from django.contrib.auth import  forms, authenticate, login
from django.core.exceptions import ValidationError
from django.forms import Form, CharField, PasswordInput
from django.utils.translation import ugettext_lazy as _

from star_wars.users.models import User


log = logging.getLogger(__file__)

class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])


class UserLoginForm(Form):
    username = CharField()
    password = CharField(widget=PasswordInput)

    class Meta:
        fields = ("username", "password")

star_wars/common/views.py
from django.views.generic import RedirectView


class MainView(RedirectView):
    pattern_name = 'films:index'

star_wars/films/views.py
# -*- coding: utf-8 -*-

from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView, ListView

from rest_framework import mixins
from rest_framework.permissions import IsAuthenticated
from rest_framework.viewsets import GenericViewSet

from star_wars.characters.models import Character
from star_wars.films.models import Film
from star_wars.films.serializers import FilmSerializer


class FilmView(LoginRequiredMixin, TemplateView):
    template_name = "index.html"

    def get(self, request, *args, **kwargs):
        queryset = Character.objects.all().order_by('?')
        kwargs.update({'characters': queryset[:5]})
        return super().get(request, *args, **kwargs)


class SearchFilmFormView(LoginRequiredMixin, ListView):
    model = Film
    search_fields = ['title', ]


class FilmApiView(mixins.ListModelMixin, GenericViewSet):
    queryset = Film.objects.all()
    serializer_class = FilmSerializer
    permission_classes = [IsAuthenticated]
    search_fields = ['title']


class FilmDetailView(LoginRequiredMixin, TemplateView):
    template_name = "film_detail.html"
    model = Film

    def get(self, request, *args, **kwargs):
        film_id = kwargs.get('id')
        kwargs['film'] = self.model.objects.get(id=film_id)
        return super().get(request, *args, **kwargs)

star_wars/url_history/views.py
# -*- coding: utf-8 -*-

from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView

from star_wars.url_history.models import UrlHistory


class UrlHistoryView(LoginRequiredMixin, ListView):
    queryset = UrlHistory.objects.all()
    template_name = 'web_history.html'

    def get_queryset(self):
        self.queryset = self.queryset.filter(user=self.request.user)
        return super().get_queryset()

star_wars/users/views.py
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import CreateView, FormView

from star_wars.users.forms import UserCreationForm, UserLoginForm
from star_wars.users.mixins import NoLoginRequiredMixin


class RegisterUserView(NoLoginRequiredMixin, CreateView):
    form_class = UserCreationForm
    template_name = 'register.html'
    success_url = reverse_lazy('films:index', args=())

    def form_valid(self, form):
        form_valid = super().form_valid(form)
        authenticate(request=self.request,
                     username=form.instance.username,
                     password=form.data.get('password'))
        login(self.request, form.instance)
        return form_valid


class LoginUserView(NoLoginRequiredMixin, FormView):
    form_class = UserLoginForm
    template_name = 'login.html'
    success_url = reverse_lazy('films:index', args=())

    def form_valid(self, form):
        form_valid = super().form_valid(form)
        try:
            user = authenticate(request=self.request,
                                username=form.data.get('username'),
                                password=form.data.get('password'))
            login(self.request, user)
        except:
            form._errors = 'Credenciales de autenticación erroneos'
            return super().form_invalid(form)
        return form_valid


class LogOutView(LoginRequiredMixin, View):
    http_method_names = ['get']

    def get(self, request, *args, **kwargs):
        logout(request)
        return HttpResponseRedirect(reverse('users:login', args=()))

star_wars/templates/403_csrf.html
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>

star_wars/templates/base.html
<!DOCTYPE html>
<html lang="es">

<head>
  {% load static i18n %}

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Star Wars - Info</title>

  <!-- Custom fonts for this template-->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
  <style>
    @font-face {
      font-family: "Star Wars";
      src: url('{% static "fonts/starwars.ttf" %}');
    }
  </style>

  <!-- Custom styles for this template-->
  <link href="{% static 'css/sb-admin-2.css' %}" rel="stylesheet">
  <link href="{% static 'content/styles.css' %}" rel="stylesheet" />
  <link rel="stylesheet" href="{% static 'css/starwars-glyphicons.css' %}">
  {% block static_block %}{% endblock %}

</head>

<body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'films:index' %}">
        <div class="sidebar-brand-icon rotate-n-15">
          <i class="swg swg-trooper-ep7"></i>
        </div>
        <div class="sidebar-brand-text mx-3">Star Wars <sup>Info</sup></div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Dashboard -->
      <li class="nav-item">
        <a class="nav-link" href="{% url 'films:index' %}">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>{% trans "Buscador de Películas" %}</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'web_history:list' %}">
          <i class="fas fa-fw fa-table"></i>
          <span>{% trans "Historial de Páginas Visitadas" %}</span></a>
      </li>
      <!-- Divider -->
      <hr class="sidebar-divider d-none d-md-block">

      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

    </ul>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

          <!-- Sidebar Toggle (Topbar) -->
          <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
          </button>

          <!-- Topbar Search -->
          <form class="d-none d-sm-inline-block form-inline mr-auto mb-sm-4 mb-md-4 mb-lg-4 mb-xl-4 ml-md-3 my-2 my-md-0 mw-100 navbar-search">
            <div class="input-group">
              <input type="text" class="form-control bg-light border-0 small"
                     placeholder="{% trans 'Buscar peliculas' %}" aria-label="Search"
                     aria-describedby="basic-addon2" name="search" id="autocomplete" autofocus>
            </div>
          </form>
          <ul class="navbar-nav ml-auto">
            <div class="topbar-divider d-none d-sm-block"></div>
            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ request.user.username }}</span>
                <img class="img-profile rounded-circle" src="{% static 'img/icon_soldier.png' %}">
              </a>
              <!-- Dropdown - User Information -->
              <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="{% url 'web_history:list' %}">
                  <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                  {% trans 'Log de Actividad' %}
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                  Logout
                </a>
              </div>
            </li>
          </ul>
        </nav>
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        <div class="container-fluid">
        {% block content %}{% endblock %}
        </div>
        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->

      <!-- Footer -->
      <footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>{% trans "Prueba técnica" %} &copy; Adam Mora Tortajada</span>
          </div>
        </div>
      </footer>
      <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">¿Desea salir?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">{% trans 'Seleccione "Logout" si desea finalizar la sesión.' %}</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">{% trans 'Cancelar' %}</button>
          <a class="btn btn-primary" href="{% url 'users:logout' %}">Logout</a>
        </div>
      </div>
    </div>
  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

  <!-- Page level plugins -->
  <script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>

  <!-- jQuery Autocomplete -->
  <script type="text/javascript" src="{% static 'scripts/jquery-1.8.2.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'scripts/jquery.mockjax.js' %}"></script>
  <script type="text/javascript" src="{% static 'src/jquery.autocomplete.js' %}"></script>
  <script>
    $('#autocomplete').autocomplete({
      serviceUrl: '{% url "films:film-list" %}',
      datatype: 'json',
      paramName: 'search',
      // beforeRender
      // formatRsult
      showNoSuggestionNotice: true,
      noSuggestionNotice: "{% trans 'Sin resultados' %}",
      transformResult: function(response) {
          return {
              suggestions: $.map(JSON.parse(response), function(dataItem) {
                  return { value: dataItem.title, data: dataItem.id, url: dataItem.url};
              })
          };
      },
      onSelect: function (suggestion) {
          window.location.href = suggestion.url;
      }
  });
  </script>

  {% block script_block %}{% endblock %}

</body>

</html>

star_wars/templates/film_detail.html
{% extends 'base.html' %}
{% load static i18n %}

{% block content %}

<div class="row">
  <div class="col-xl-4 col-lg-4">
    <div class="card shadow mb-4">
      <!-- Card Header - Dropdown -->
      <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">{% trans "Imagen de la Película" %}</h6>
      </div>
      <!-- Card Body -->
      <div class="card-body">
        <img src="{{film.image.url}}" style="max-width: 100%;"/>
      </div>
    </div>
  </div>
  <div class="col-xl-8 col-lg-8">
      <div class="card shadow mb-4">
        <!-- Card Header - Dropdown -->
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
          <h6 class="m-0 font-weight-bold text-primary">
            {% trans "Titulo" %}: <span style="font-family: 'Star Wars'; color: black">
            {% trans "Episode" %} {{film.episode_id}}: {{film.title}}
          </span>
          </h6>
        </div>
        <!-- Card Body -->
        <div class="card-body">
          <b>Director:</b> {{film.director}}<br>
          <b>Productor:</b> {{film.producer}}<br>
          <b>Fecha de lanzamiento:</b> {{film.release_date}}<br><br>
          <b>Descripción:</b><br>
          {{film.opening_crawl}}
        </div>
      </div>
    </div>
</div>

<div class="row">
  <!-- Area Chart -->
  <div class="col-xl-12 col-lg-12">
    <div class="card shadow mb-4">
      <!-- Card Header - Dropdown -->
      <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">Carrusel de personajes pertenecientes a la película</h6>
      </div>
      <!-- Card Body -->
      <div class="card-body">
        <div class="chart-area">
          <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
              <li data-target="#carouselExampleIndicators" data-slide-to="forloop.counter0"
                  class="{% if forloop.counter0 == 0 %}active{% endif %}"></li>
            </ol>
            <div class="carousel-inner">
              {% for character in film.characters.all %}
              <div class="carousel-item {% if forloop.counter0 == 0 %}active{% endif %}">
                <img class="d-block w-100" src="{{character.random_image.url}}" alt="{{character.name}}"
                     style="height: 18vw; object-fit: cover;">
                <div class="carousel-caption d-none d-md-block"
                     style="font-family: 'Star Wars'; text-shadow: 4px 4px 4px #aaa; color: yellow;">
                  <h5>{{character.name}}</h5>
                  <p>{{character.description}}</p>
                </div>
              </div>
              {% endfor %}
            </div>
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

star_wars/templates/index.html
{% extends 'base.html' %}
{% load static i18n %}

{% block films %}active{% endblock %}

{% block content %}
<div class="row">
  <!-- Area Chart -->
  <div class="col-xl-12 col-lg-12">
    <div class="card shadow mb-4">
      <!-- Card Header - Dropdown -->
      <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">Carrusel de Personajes</h6>
      </div>
      <!-- Card Body -->
      <div class="card-body">
        <div class="chart-area">
          <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
              <li data-target="#carouselExampleIndicators" data-slide-to="forloop.counter0"
                  class="{% if forloop.counter0 == 0 %}active{% endif %}"></li>
            </ol>
            <div class="carousel-inner">
              {% for character in characters %}
              <div class="carousel-item {% if forloop.counter0 == 0 %}active{% endif %}">
                <img class="d-block w-100" src="{{character.random_image.url}}" alt="{{character.name}}"
                     style="height: 23vw; object-fit: cover;">
                <div class="carousel-caption d-none d-md-block"
                     style="font-family: 'Star Wars'; text-shadow: 4px 4px 4px #aaa; color: yellow;">
                  <h5>{{character.name}}</h5>
                  <p>{{character.description}}</p>
                </div>
              </div>
              {% endfor %}
            </div>
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}


{% block script_block %}

{% endblock %}

star_wars/templates/login.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% load static i18n %}
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Star Wars</title>

  <!-- Custom fonts for this template-->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'css/sb-admin-2.css' %}" rel="stylesheet">

</head>

<body class="bg-gradient-primary" style="background: url('{% static 'img/login_background.jpg' %}');">

  <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
              <div class="col-lg-6">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">{% trans "Bienvenido" %}</h1>
                  </div>
                  <form class="user" method="POST" action=".">
                    {% csrf_token %}
                    {{ form.errors }}
                    <div class="form-group">
                      <input type="text" class="form-control form-control-user" id="exampleInputEmail" name="username"
                             aria-describedby="emailHelp" placeholder="{% trans 'Nombre de usuario' %}">
                    </div>
                    <div class="form-group">
                      <input type="password" class="form-control form-control-user" name="password"
                             id="exampleInputPassword" placeholder="{% trans 'Contraseña' %}">
                    </div>
                    <button type="submit" class="btn btn-primary btn-user btn-block">
                      Login
                    </button>
                  </form>
                  <hr>
                  <div class="text-center">
                    <a class="small" href="{% url 'users:register' %}">{% trans "Crear una cuenta" %}</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

</body>

</html>